### ISSUE TITLE
Crashing on 1.8.9

### ISSUE THREAD

**Issue by YEETItUp4** [SteveKunG/SkyBlockcatia#69]
Whenever I use the mod it makes my forge crash. Here is a pic of it:
![image](https://user-images.githubusercontent.com/78773956/107432984-b8365680-6af6-11eb-9125-6e4b545812d9.png)
Ty

**Comment by brandvdo** [comment]
Same here

**Comment by Cuhstom** [comment]
I am having this same issue. I've tried everything and I don't know how to fix it, because I want to use Skyblockcatia. If you find a solution or have any new updates please lmk here.

**Comment by Devviedehm** [comment]
Click the View crash report button and add the file here, otherwise it's hard to help.

Send a screenshot of the mods folder.

Additional steps you can also take, complete guesswork without actual crash log:
-Make sure you're running Forge Latest (2318).
-Update to OptiFine M5
-Update to Patcher 1.5.1
-Update to SkyBlockcatia 1.0.16

**Comment by Cuhstom** [comment]
[crash-2021-02-17_13.39.22-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/5999212/crash-2021-02-17_13.39.22-client.txt)
![image](https://user-images.githubusercontent.com/79226484/108281298-babf2e80-713c-11eb-88a2-fa5b53556b69.png)

**Comment by Devviedehm** [comment]
You're using the 1.16 version of SkyBlockcatia in the 1.8.9 version of Minecraft. You probably want to download the 1.8.9 version, currently should be "SkyBlockcatia-1.8.9-1.0.16":

https://www.curseforge.com/minecraft/mc-mods/skyblockcatia/files/all?filter-game-version=1738749986%3a4

**Comment by SteveKunG** [comment]
Thanks for help! @Devviedehm
